name: Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ddsupportkb \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING_DDAI }}" \
              --destination docs/github/docs/blob/master \
              --source ./
